# (PART\*) Basics {-}

# The Ames housing data

**Learning objectives:**

- Explain why **exploratory data analysis** is an essential component of any modeling project.
- Recognize the **Ames housing data** - variables, context, and past cleaning.
- Explain when it makes sense to **log-transform data.**

## Pittsburgh: a parallel real world example

[Conor Tompkins](https://twitter.com/conor_tompkins) presented a fantastic overview of home sale price modeling by taking us through his recent project on Pittsburgh home sale price modeling, including discussions about his **exploratory data analysis**, motivations behind **log-transforming** sale data, and thoughts about **inflation-adjusting** historical sale prices. 

You can check out the discussion and presentation in the Cohort 1 meeting video for this week!

Code Repository here: https://github.com/conorotompkins/model_allegheny_house_sales

Shiny app: https://conorotompkins.shinyapps.io/house_sale_estimator/


## Videos de las reuniones

### Cohorte 1

`r knitr::include_url("https://www.youtube.com/embed/vaqsOagFJbY")`

<details>
  <summary> Chat de la reunión </summary>
  
```
00:27:35	Justin Dollman:	Cinco log dólares!
00:42:15	Roberto Villegas-Diaz:	Gracias por presentar! 
00:43:22	Roberto Villegas-Diaz:	https://docs.google.com/spreadsheets/d/1apDY5yyimVUwebhZvTwM3P7Pysa9ztZvj4EUF_KFVdw/edit?usp=sharing
00:44:16	Armando Guzmán Mx:	Sí, la próxima sesión está bien! je!
```
</details>
