--- 
title: "Modelado Tidy con R - Club de Lectura"
author: "La Comunidad de Aprendizaje en línea R4DS"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
github-repo: r4ds/bookclub-tmwr_es
description: "Este es el producto del Club de Lectura - Modelado Tidy con R de la Comunidad de Aprendizaje en línea R4DS."
---

# Bienvenida {-}

Este es un suplemento para el libro [Modelado Tidy con R](https://www.tmwr.org/) por Max Kuhn y Julia Silge.
Este suplemento está disponible en [r4ds.io/tmwr_es](https://r4ds.io/tmwr_es).

Este sitio es mantenido por la [Comunidad de Aprendizaje en línea R4DS](https://rfordatasci.com). Sigue y [únete a la comunidad](https://r4ds.io/join) para participar.

Este suplemento sigue el [código de conducta de la Comunidad de Aprendizaje en línea R4DS](https://r4ds.io/conduct).

## Reuniones del club de lectura {-}

- Cada semana, unx voluntarix presentará un capítulo del libro.
  - **Esta es la mejor manera de aprender los contenidos.**
- Las presentaciones usualmente consisten de una revisión de los contenidos, una discusión y/o una demostración de los conceptos presentados en el capítulo.
- Detalles adicionales sobre como presentar, pueden ser encontrados en el [repositorio de GitHub](https://github.com/r4ds/bookclub-tmwr).
- Las presentaciones serán grabadas y estarán disponibles en el [canal de YouTube de la Comunidad de Aprendizaje en línea R4DS](https://r4ds.io/youtube).
